services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: langchain-chatbot
    ports:
      - "8500:8500"
    volumes:
      - ./secret.yaml:/secret.yaml
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8500
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: always